name = "lyceum"
version = "0.1.0"
defaultTargets = ["lyceum"]

[[lean_lib]]
name = "Lyceum"
roots = ["Lyceum"]

[[lean_lib]] # New lib for core modules
name = "Lyceum.Core"
roots = ["Lyceum.Core"]

[[lean_exe]]
name = "lyceum"
root = "Main"

[[lean_exe]]
name = "test"
root = "Test"

[[require]]
name = "nomos"
path = "../nomos"

[[require]]
name = "LeanTensor"
path = "../LeanTensor"
